<?php
/**
 * PaymentDisputeApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\EbayFulFillmentClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * The version of the OpenAPI document: v1.19.2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\EbayFulFillmentClient\Test\Api;

use \OpenAPI\EbayFulFillmentClient\Configuration;
use \OpenAPI\EbayFulFillmentClient\ApiException;
use \OpenAPI\EbayFulFillmentClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PaymentDisputeApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\EbayFulFillmentClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PaymentDisputeApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for acceptPaymentDispute
     *
     * Accept Payment Dispute.
     *
     */
    public function testAcceptPaymentDispute()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addEvidence
     *
     * Add an Evidence File.
     *
     */
    public function testAddEvidence()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for contestPaymentDispute
     *
     * Contest Payment Dispute.
     *
     */
    public function testContestPaymentDispute()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fetchEvidenceContent
     *
     * Get Payment Dispute Evidence File.
     *
     */
    public function testFetchEvidenceContent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getActivities
     *
     * Get Payment Dispute Activity.
     *
     */
    public function testGetActivities()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPaymentDispute
     *
     * Get Payment Dispute Details.
     *
     */
    public function testGetPaymentDispute()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPaymentDisputeSummaries
     *
     * Search Payment Dispute by Filters.
     *
     */
    public function testGetPaymentDisputeSummaries()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateEvidence
     *
     * Update evidence.
     *
     */
    public function testUpdateEvidence()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for uploadEvidenceFile
     *
     * Upload an Evidence File.
     *
     */
    public function testUploadEvidenceFile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
